version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app_task
    ports:
      - "5002:5002"
    networks:
      private-net:
        aliases:
          - local.task-api

networks:
  private-net:
    external: true
